// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyjO9fOAW9j94uIwMolxl1ZHgis7WDcEE',
    appId: '1:477347763660:web:5c08774ff5a74f304df969',
    messagingSenderId: '477347763660',
    projectId: 'reaction-cards-8a90b',
    authDomain: 'reaction-cards-8a90b.firebaseapp.com',
    storageBucket: 'reaction-cards-8a90b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaQ5Zq58Vtuf9aS0EntZxwDlCGgbyeXbU',
    appId: '1:477347763660:android:d4ad88f9d4926eb74df969',
    messagingSenderId: '477347763660',
    projectId: 'reaction-cards-8a90b',
    storageBucket: 'reaction-cards-8a90b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrF2SYJ6NqFAcL4inB19tNLLbJnZdhMsA',
    appId: '1:477347763660:ios:43cae0bb2099b1e24df969',
    messagingSenderId: '477347763660',
    projectId: 'reaction-cards-8a90b',
    storageBucket: 'reaction-cards-8a90b.firebasestorage.app',
    iosBundleId: 'com.example.reactionCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrF2SYJ6NqFAcL4inB19tNLLbJnZdhMsA',
    appId: '1:477347763660:ios:43cae0bb2099b1e24df969',
    messagingSenderId: '477347763660',
    projectId: 'reaction-cards-8a90b',
    storageBucket: 'reaction-cards-8a90b.firebasestorage.app',
    iosBundleId: 'com.example.reactionCards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyjO9fOAW9j94uIwMolxl1ZHgis7WDcEE',
    appId: '1:477347763660:web:0ed534caa9b4197a4df969',
    messagingSenderId: '477347763660',
    projectId: 'reaction-cards-8a90b',
    authDomain: 'reaction-cards-8a90b.firebaseapp.com',
    storageBucket: 'reaction-cards-8a90b.firebasestorage.app',
  );
}
